### ISSUE TITLE
Schema Validation Broken 6.11.0

### ISSUE THREAD

**Issue by knocknarea** [TIBCOSoftware/jasperreports#118]
When trying to Jasper reports, the compiler breaks because the publicly available XSD (http://jasperreports.sourceforge.net/xsd/jasperreport.xsd) does not contain the new element textAdjust

Please advise on where I can get the lastest XSD that reflects the changes to 6.11.0?

Note: I cannot switch off schema validation as this **different** error occurs

https://community.jaspersoft.com/questions/528161/error-compiling-ant

Given that 6.11.0 is a breaking change from previous versions can you ensure that there is a publicly available XSD on which to validate, that is correct for 6.11.0. I am in a pickle at the moment over this because iReport has replaced all instances of stretchWithOverflow with textAdjust and I cannot compile my reports.

**Comment by teodord** [comment]
JasperReports Library contains its own XSD and does not rely on availability of Internet connection to compile its own reports. You have to admit that would be a little crazy.
Having said that, I don't understand what happens in your case. So to put this matter to rest, I simply updated the XSD files at the public location.

**Comment by knocknarea** [comment]
@teodord 
I am using https://github.com/alexnederlof/Jasper-report-maven-plugin to compile the reports as part of my maven build, maybe it is pulling the publicly version of the XSD to validate the xml?

Anyhow, thank you for the fast response.

**Comment by knocknarea** [comment]
@teodord I am still getting this error.

I use jasper studio in eclipse and it works fine previewing the reports. I have configured jasper studio to output the jrxml to be 6.11.0 compatible. However when I try to compile the report as part of the build I get this error and it does seem to be originating within the jasper compiler, maybe it's a class path issue, but I don't have any version below 6.10.0 in the class path, so I don't know where it's picking up the wrong XSD from.

[ERROR] Could not compile attendance-ncs.jrxml because org.xml.sax.SAXParseException; lineNumber: 315; columnNumber: 69; cvc-complex-type.3.2.2: Attribute 'textAdjust' is not allowed to appear in element 'textField'.
net.sf.jasperreports.engine.JRException: org.xml.sax.SAXParseException; lineNumber: 315; columnNumber: 69; cvc-complex-type.3.2.2: Attribute 'textAdjust' is not allowed to appear in element 'textField'.
	at net.sf.jasperreports.engine.xml.JRXmlLoader.loadXML(JRXmlLoader.java:302)
	at net.sf.jasperreports.engine.xml.JRXmlLoader.loadXML(JRXmlLoader.java:285)
	at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:274)
	at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:248)
	at net.sf.jasperreports.engine.JasperCompileManager.compileToStream(JasperCompileManager.java:308)
	at net.sf.jasperreports.engine.JasperCompileManager.compileReportToStream(JasperCompileManager.java:588)
	at com.alexnederlof.jasperreport.CompileTask.call(CompileTask.java:63)
	at com.alexnederlof.jasperreport.CompileTask.call(CompileTask.java:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
