### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/digester/Rule

### ISSUE THREAD

**Issue by rishikeshvijay** [TIBCOSoftware/jasperreports#127]
we upgraded jasper reports to 6.11.0, since then getting the error, we have all the dependent libraries added to the classpath, tried with digester3-3.2, digester 2.1 both jars

Caused by: java.lang.NoClassDefFoundError: org/apache/commons/digester/Rule
        at net.sf.jasperreports.components.ComponentsExtensionsRegistryFactory.<clinit>(ComponentsExtensionsRegistryFactory.java:109)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at net.sf.jasperreports.engine.util.JRClassLoader.loadClassForRealName(JRClassLoader.java:173)
        at net.sf.jasperreports.engine.util.JRClassLoader.loadClassForName(JRClassLoader.java:131)
        at net.sf.jasperreports.engine.util.ClassUtils.instantiateClass(ClassUtils.java:60)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.instantiateRegistry(DefaultExtensionsRegistry.java:298)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.loadRegistries(DefaultExtensionsRegistry.java:274)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.loadRegistries(DefaultExtensionsRegistry.java:194)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.getRegistries(DefaultExtensionsRegistry.java:157)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.getExtensions(DefaultExtensionsRegistry.java:129)
        at net.sf.jasperreports.engine.util.JRStyledTextParser.<clinit>(JRStyledTextParser.java:86)
        at net.sf.jasperreports.engine.fill.JRBaseFiller.<init>(JRBaseFiller.java:116)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(JRVerticalFiller.java:79)
        at net.sf.jasperreports.engine.fill.JRFiller.createBandReportFiller(JRFiller.java:251)
        at net.sf.jasperreports.engine.fill.JRFiller.createReportFiller(JRFiller.java:272)
        at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:114)
        at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:103)
        at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:530)
        at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:954)

But repeating the same error. Any help is really appreciated.

**Comment by teodord** [comment]
Are you deploying JasperReports inside a web application? What kind of Java application is it?

**Comment by rishikeshvijay** [comment]
We are using jasper reports jar within our application to generate reports, running on Tomcat server

**Comment by teodord** [comment]
JasperReports uses Digester 2.1. Because Digester3 has different package names, it acts like a totally different library that has nothing to do with what JasperReports needs. So you can remove Digester3 from classpath, unless you are using it yourself in your own application.
The error you have clearly indicates that Digester 2.1 is not found in your application classpath.
You need to check that again.
