### ISSUE TITLE
Facing issue while using jasperreports.jar 6.13.0 for compiling .jrxml files 

### ISSUE THREAD

**Issue by Harshad-Panmand** [TIBCOSoftware/jasperreports#144]
We are using below ant target for compiling .jrxml files which are present in our application source folder.

    <taskdef name="jrc" classname="net.sf.jasperreports.ant.JRAntCompileTask">
        <classpath refid="classpath" />
    </taskdef>

We are using ant build framework to compile application source code with jrxml files.
we are getting the below issue.

**NOTE: we have upgraded our jasperreports.jar from 6.8.1 to 6.13.0**

java.lang.NullPointerException
               at net.sf.jasperreports.engine.design.JRAbstractCompiler.deleteSourceFiles(JRAbstractCompiler.java:407)
               at net.sf.jasperreports.engine.design.JRAbstractCompiler.compileReport(JRAbstractCompiler.java:281)
               at net.sf.jasperreports.engine.JasperCompileManager.compile(JasperCompileManager.java:358)
               at net.sf.jasperreports.engine.JasperCompileManager.compileToFile(JasperCompileManager.java:274)
               at net.sf.jasperreports.engine.JasperCompileManager.compileToFile(JasperCompileManager.java:256)
               at net.sf.jasperreports.ant.JRAntCompileTask.compile(JRAntCompileTask.java:405)
               at net.sf.jasperreports.ant.JRAntCompileTask.execute(JRAntCompileTask.java:252)
               at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
               at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
               at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               at java.base/java.lang.reflect.Method.invoke(Method.java:566)
               at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
               at org.apache.tools.ant.Task.perform(Task.java:350)
               at org.apache.tools.ant.Target.execute(Target.java:449)
               at org.apache.tools.ant.Target.performTasks(Target.java:470)
               at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
               at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
               at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
               at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
               at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
               at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
               at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               at java.base/java.lang.reflect.Method.invoke(Method.java:566)
               at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
               at org.apache.tools.ant.Task.perform(Task.java:350)
               at org.apache.tools.ant.Target.execute(Target.java:449)
               at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:173)
               at org.apache.tools.ant.taskdefs.ImportTask.importResource(ImportTask.java:221)
               at org.apache.tools.ant.taskdefs.ImportTask.execute(ImportTask.java:165)
               at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
               at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
               at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               at java.base/java.lang.reflect.Method.invoke(Method.java:566)
               at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
               at org.apache.tools.ant.Task.perform(Task.java:350)
               at org.apache.tools.ant.Target.execute(Target.java:449)
               at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:173)
               at org.apache.tools.ant.taskdefs.ImportTask.importResource(ImportTask.java:221)
               at org.apache.tools.ant.taskdefs.ImportTask.execute(ImportTask.java:165)
               at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
               at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
               at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               at java.base/java.lang.reflect.Method.invoke(Method.java:566)
               at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
               at org.apache.tools.ant.Task.perform(Task.java:350)
               at org.apache.tools.ant.Target.execute(Target.java:449)
               at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:184)
               at org.apache.tools.ant.ProjectHelper.configureProject(ProjectHelper.java:93)
               at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:393)
               at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:312)
               at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:227)
               at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
               at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
               at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               at java.base/java.lang.reflect.Method.invoke(Method.java:566)
               at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
               at org.apache.tools.ant.Task.perform(Task.java:350)
               at java.base/java.util.Vector.forEach(Vector.java:1387)
               at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
               at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
               at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
               at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               at java.base/java.lang.reflect.Method.invoke(Method.java:566)
               at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
               at org.apache.tools.ant.Task.perform(Task.java:350)
               at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:391)
               at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
               at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
               at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               at java.base/java.lang.reflect.Method.invoke(Method.java:566)
               at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
               at org.apache.tools.ant.Task.perform(Task.java:350)
               at org.apache.tools.ant.Target.execute(Target.java:449)
               at org.apache.tools.ant.Target.performTasks(Target.java:470)
               at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
               at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
               at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
               at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
               at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
               at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
               at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               at java.base/java.lang.reflect.Method.invoke(Method.java:566)
               at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
               at groovy.util.AntBuilder.performTask(AntBuilder.java:327)
               at groovy.util.AntBuilder.nodeCompleted(AntBuilder.java:272)
               at groovy.util.BuilderSupport.doInvokeMethod(BuilderSupport.java:154)
               at groovy.util.AntBuilder.doInvokeMethod(AntBuilder.java:207)
               at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:67)
               at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
               at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
               at ModuleDescriptor.genDescriptor(ModuleDescriptor.groovy:131)
               at ModuleDescriptor.genDescriptor(ModuleDescriptor.groovy)
               at ModuleDescriptor.ensureFileExists(ModuleDescriptor.groovy:95)
               at ModuleDescriptor.ensureFileExists(ModuleDescriptor.groovy)
               at ModuleDescriptor$ensureFileExists$0.call(Unknown Source)
               at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:80)
               at ModuleSort$_orderModules_closure1.doCall(ModuleSort.groovy:36)
               at jdk.internal.reflect.GeneratedMethodAccessor279.invoke(Unknown Source)
               at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               at java.base/java.lang.reflect.Method.invoke(Method.java:566)
               at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
               at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
               at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
               at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
               at groovy.lang.Closure.call(Closure.java:414)
               at groovy.lang.Closure.call(Closure.java:430)
               at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2040)
               at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2025)
               at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2066)
               at org.codehaus.groovy.runtime.dgm$163.invoke(Unknown Source)
               at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
               at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
               at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
               at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
               at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
               at ModuleSort.orderModules(ModuleSort.groovy:32)
               at ModuleSort$orderModules.call(Unknown Source)
               at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
               at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
               at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
               at GenModuleOrder.run(GenModuleOrder.groovy:23)
               at org.codehaus.groovy.ant.Groovy.parseAndRunScript(Groovy.java:491)
               at org.codehaus.groovy.ant.Groovy.execGroovy(Groovy.java:438)
               at org.codehaus.groovy.ant.Groovy.execute(Groovy.java:303)
               at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
               at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
               at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               at java.base/java.lang.reflect.Method.invoke(Method.java:566)
               at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
               at org.apache.tools.ant.Task.perform(Task.java:350)
               at org.apache.tools.ant.Target.execute(Target.java:449)
               at org.apache.tools.ant.Target.performTasks(Target.java:470)
               at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
               at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
               at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
               at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
               at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
               at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
               at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               at java.base/java.lang.reflect.Method.invoke(Method.java:566)
               at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
               at org.apache.tools.ant.Task.perform(Task.java:350)
               at org.apache.tools.ant.Target.execute(Target.java:449)
               at org.apache.tools.ant.Target.performTasks(Target.java:470)
               at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
               at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
               at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
               at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
               at org.apache.tools.ant.Main.runBuild(Main.java:830)
               at org.apache.tools.ant.Main.startAnt(Main.java:223)
               at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
               at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)

**Comment by dadza** [comment]
Already fixed at https://github.com/TIBCOSoftware/jasperreports/commit/3e1b8ab289e0d7d405be6fb3ddada059f77d8282

See https://stackoverflow.com/a/63072294/983559 for ways to workaround the problem with JasperReports 6.13.0.
