### ISSUE TITLE
NullPointerException JRLoader.loadObject(jasperPrintStream)

### ISSUE THREAD

**Issue by nickvl** [TIBCOSoftware/jasperreports#156]
Jasper library: 6.15.0
A Critical problem with some reports during a try to read existing jasper print:

```
Caused by: java.lang.NullPointerException: null
	at net.sf.jasperreports.engine.fill.JRVirtualizationContext.getCachedTemplate(JRVirtualizationContext.java:296)
	at net.sf.jasperreports.engine.fill.JRVirtualizationContext.resolveSerializedObject(JRVirtualizationContext.java:535)
	at net.sf.jasperreports.engine.fill.VirtualizationObjectInputStream.resolveObject(VirtualizationObjectInputStream.java:52)
	at java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1698)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2366)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:613)
	at net.sf.jasperreports.engine.fill.JRTemplatePrintElement.readObject(JRTemplatePrintElement.java:374)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1185)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2257)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:483)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:441)
	at java.util.ArrayList.readObject(ArrayList.java:799)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1185)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2257)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:483)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:441)
	at net.sf.jasperreports.engine.base.ElementsBlock.readObject(ElementsBlock.java:464)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1185)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2257)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2054)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1635)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2366)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2290)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2366)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2290)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:483)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:441)
	at java.util.concurrent.ConcurrentHashMap.readObject(ConcurrentHashMap.java:1445)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1185)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2257)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
	at java.io.ObjectInputStream.access$800(ObjectInputStream.java:215)
	at java.io.ObjectInputStream$GetFieldImpl.readFields(ObjectInputStream.java:2531)
	at java.io.ObjectInputStream.readFields(ObjectInputStream.java:653)
	at net.sf.jasperreports.engine.fill.JRVirtualizationContext.readObject(JRVirtualizationContext.java:415)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1185)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2257)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:483)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:441)
	at java.util.HashSet.readObject(HashSet.java:341)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1185)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2257)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
	at java.io.ObjectInputStream.access$800(ObjectInputStream.java:215)
	at java.io.ObjectInputStream$GetFieldImpl.readFields(ObjectInputStream.java:2531)
	at java.io.ObjectInputStream.readFields(ObjectInputStream.java:653)
	at net.sf.jasperreports.engine.fill.JRVirtualizationContext.readObject(JRVirtualizationContext.java:415)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1185)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2257)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:483)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:441)
	at net.sf.jasperreports.engine.base.ElementsBlock.readObject(ElementsBlock.java:456)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1185)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2257)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2366)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2290)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:483)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:441)
	at net.sf.jasperreports.engine.base.JRVirtualPrintPage.readObject(JRVirtualPrintPage.java:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1185)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2257)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:483)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:441)
	at java.util.ArrayList.readObject(ArrayList.java:799)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1185)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2257)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2366)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2290)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2366)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:613)
	at net.sf.jasperreports.engine.JasperPrint.readObject(JasperPrint.java:1039)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1185)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2257)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:483)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:441)
	at net.sf.jasperreports.engine.util.JRLoader.loadObject(JRLoader.java:278)
	at net.sf.jasperreports.engine.util.JRLoader.loadObject(JRLoader.java:262)
	at net.sf.jasperreports.rm.generation.JasperReportGenerator.read(JasperReportGenerator.java:223)
	... 10 common frames omitted

```
it happens because it sees null cachedTemplates during invocation GetField fields = in.readFields(); in JRVirtualizationContext

```
private void readObject(java.io.ObjectInputStream in) throws IOException, ClassNotFoundException
	{
		setThreadJasperReportsContext();

		GetField fields = in.readFields();
		cachedRenderers = (Map<String, Renderable>) fields.get("cachedRenderers", null);
		cachedTemplates = (Map<String, JRTemplateElement>) fields.get("cachedTemplates", null);
		virtualizableLists = (Map<PrintElementId, VirtualizableElementList>) fields.get("virtualizableLists", null);
		readOnly = fields.get("readOnly", false);
		// use configured default if serialized by old version
		pageElementSize = fields.get("pageElementSize", JRPropertiesUtil.getInstance(jasperReportsContext).getIntegerProperty(
				JRVirtualPrintPage.PROPERTY_VIRTUAL_PAGE_ELEMENT_SIZE, 0));
		
		setThreadVirtualizer();
		
		initLock();
	}
```

This issue does not exist in jasper library 6.7.0

**Comment by luigifioravanti** [comment]
I have the same issue.
I tried with the following piece of code and I get the NullPointerException at the last line.

```
JRSwapFile swapFile = new JRSwapFile(this.baseFolder.getAbsolutePath(), 1024, 1024);
JRVirtualizer virtualizer = new JRSwapFileVirtualizer(10, swapFile);
JRVirtualizationHelper.setThreadVirtualizer(virtualizer);

JasperPrint jasperPrint = JasperFillManager.fillReport(compiledReportFile.getAbsolutePath(), reportParametersValuesTmp, conn);
JRSaver.saveObject(jasperPrint, filledReportFile.getAbsolutePath());
JasperPrint JasperPrintReloaded = JRLoader.loadJasperPrintFromFile(filledReportFile.getAbsolutePath(), virtualizer);

```
It seems that in the loader the original JRVirtualizationContext is lost.

**Comment by luigifioravanti** [comment]
It seem that the issue is related with the number of element in the JasperPrint object: with a small number of elements (probably utill they fit in one virtual page) the issue do not happen.

**Comment by luigifioravanti** [comment]
The issue is present starting from version 6.12.x; in version 6.11.0 the above code works perfectly.
