### ISSUE TITLE
FontUtil throws NullPointerException

### ISSUE THREAD

**Issue by quaff** [TIBCOSoftware/jasperreports#16]
I have an application upgrade jasperreports from 6.0.3 to 6.5.0, It throws NullPointerException
```
java.lang.NullPointerException: null
	at net.sf.jasperreports.engine.fonts.FontUtil.getFontInfo(FontUtil.java:210) ~[jasperreports-6.5.0.jar:6.5.0]
	at net.sf.jasperreports.engine.util.JRStyledTextUtil.loadFamilyFonts(JRStyledTextUtil.java:454) ~[jasperreports-6.5.0.jar:6.5.0]
	at net.sf.jasperreports.engine.util.JRStyledTextUtil.getFamilyFonts(JRStyledTextUtil.java:441) ~[jasperreports-6.5.0.jar:6.5.0]
	at net.sf.jasperreports.engine.util.JRStyledTextUtil.getFamilyFonts(JRStyledTextUtil.java:432) ~[jasperreports-6.5.0.jar:6.5.0]
	at net.sf.jasperreports.engine.util.JRStyledTextUtil.resolveFonts(JRStyledTextUtil.java:190) ~[jasperreports-6.5.0.jar:6.5.0]
	at net.sf.jasperreports.engine.util.JRStyledTextUtil.resolveFonts(JRStyledTextUtil.java:170) ~[jasperreports-6.5.0.jar:6.5.0]
	at net.sf.jasperreports.engine.fill.JRFillTextElement.getProcessedStyledText(JRFillTextElement.java:612) ~[jasperreports-6.5.0.jar:6.5.0]
	at net.sf.jasperreports.engine.fill.JRFillTextElement.chopTextElement(JRFillTextElement.java:656) ~[jasperreports-6.5.0.jar:6.5.0]
	at net.sf.jasperreports.engine.fill.JRFillTextField.prepare(JRFillTextField.java:777) ~[jasperreports-6.5.0.jar:6.5.0]
	at net.sf.jasperreports.engine.fill.JRFillElementContainer.prepareElements(JRFillElementContainer.java:542) ~[jasperreports-6.5.0.jar:6.5.0]
	at net.sf.jasperreports.engine.fill.JRFillBand.fill(JRFillBand.java:438) ~[jasperreports-6.5.0.jar:6.5.0]
	at net.sf.jasperreports.engine.fill.JRFillBand.fill(JRFillBand.java:413) ~[jasperreports-6.5.0.jar:6.5.0]
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillTitle(JRVerticalFiller.java:310) ~[jasperreports-6.5.0.jar:6.5.0]
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReportStart(JRVerticalFiller.java:244) ~[jasperreports-6.5.0.jar:6.5.0]
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:99) ~[jasperreports-6.5.0.jar:6.5.0]
	at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:609) ~[jasperreports-6.5.0.jar:6.5.0]
	at net.sf.jasperreports.engine.fill.BaseReportFiller.fill(BaseReportFiller.java:405) ~[jasperreports-6.5.0.jar:6.5.0]
	at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:140) ~[jasperreports-6.5.0.jar:6.5.0]
	at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:667) ~[jasperreports-6.5.0.jar:6.5.0]
	at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:983) ~[jasperreports-6.5.0.jar:6.5.0]
```
`name.equals(face.getFont().getFamily())` face.getFont() could be null

**Comment by teodord** [comment]
Can you attach the custom font extension that causes this, if you have one?

Thank you,
Teodor

**Comment by quaff** [comment]
[font-simsun-1.0.jar.zip](https://github.com/TIBCOSoftware/jasperreports/files/1594909/font-simsun-1.0.jar.zip)

**Comment by teodord** [comment]
I took the font extension file you provided, removed its zip extension, placed it in a /lib folder inside the /demo/samples/unicode folder of the JRL project, modified the sample Ant classpath to pick it up and used "宋体" as fontName in the sample report (see attached [patch.txt](https://github.com/TIBCOSoftware/jasperreports/files/1596441/patch.txt)
).
I was able to run the sample without problem.

What operating system are you using and what version of Java? Can you try do the same test on your side to see if the problem occurs with one of our own samples in the project source tree?

**Comment by quaff** [comment]
[jasperreports-demo.zip](https://github.com/TIBCOSoftware/jasperreports/files/1596623/jasperreports-demo.zip)
There is another jar contains two file `jasperreports_extension.properties` and `zhfonts.xml`, I delete unrelated files and rename it to `other.jar`

**Comment by quaff** [comment]
Thanks, It works.
