### ISSUE TITLE
Font "DejaVu Sans" is not available to the JVM - Java 8

### ISSUE THREAD

**Issue by danielpeintner** [TIBCOSoftware/jasperreports#162]
Hi,

Thank you for your great work.
I did try to update the JasperReports dependencies from version `6.15.0` to `6.16.0` with the same set of dependencies
* `jasperreports `and
* `jasperreports-fonts`

On JVM 8 I get the following stacktrace while on JVM 11 it works just fine.
(operating system is always Windows 10)

Thanks!

```
net.sf.jasperreports.engine.util.JRFontNotFoundException: Font "DejaVu Sans" is not available to the JVM. See the Javadoc for more details.
	at net.sf.jasperreports.engine.fonts.FontUtil.checkAwtFont(FontUtil.java:603)
	at net.sf.jasperreports.engine.fill.SimpleTextLineWrapper.loadFont(SimpleTextLineWrapper.java:384)
	at net.sf.jasperreports.engine.fill.SimpleTextLineWrapper.getGeneralFontInfo(SimpleTextLineWrapper.java:354)
	at net.sf.jasperreports.engine.fill.SimpleTextLineWrapper.createFontInfo(SimpleTextLineWrapper.java:294)
	at net.sf.jasperreports.engine.fill.SimpleTextLineWrapper.start(SimpleTextLineWrapper.java:256)
	at net.sf.jasperreports.engine.fill.TextMeasurer.measure(TextMeasurer.java:555)
	at net.sf.jasperreports.engine.fill.JRFillTextElement.chopTextElement(JRFillTextElement.java:654)
	at net.sf.jasperreports.engine.fill.JRFillTextField.prepare(JRFillTextField.java:812)
	at net.sf.jasperreports.engine.fill.JRFillElementContainer.prepareElements(JRFillElementContainer.java:542)
	at net.sf.jasperreports.engine.fill.JRFillBand.fill(JRFillBand.java:453)
	at net.sf.jasperreports.engine.fill.JRFillBand.fill(JRFillBand.java:428)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillBandNoOverflow(JRVerticalFiller.java:450)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillPageHeader(JRVerticalFiller.java:411)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReportStart(JRVerticalFiller.java:260)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:110)
	at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:621)
	at net.sf.jasperreports.engine.fill.BaseReportFiller.fill(BaseReportFiller.java:433)
	at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:162)
	at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:145)
	at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:758)
	at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:1074)
```

**Comment by shertage** [comment]
Hi, in order to reproduce the issue, we need some more info regarding the Java platform (Oracle, OpenJDK), the jvm build number, the Windows OS build number. In case you updated the JasperReports dependencies using maven, we also need the maven version.
Thank you.

**Comment by danielpeintner** [comment]
Hi,
I did try once again the same: changing my Maven Dependency from 

```
		<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>jasperreports</artifactId>
			<version>6.15.0</version>
		</dependency>
		<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>jasperreports-fonts</artifactId>
			<version>6.15.0</version>
		</dependency>
```

to

```
		<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>jasperreports</artifactId>
			<version>6.16.0</version>
		</dependency>
		<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>jasperreports-fonts</artifactId>
			<version>6.16.0</version>
		</dependency>
```

This time it worked. Not sure whether it was a *local* Maven caching issue.

Windows 10, Version 1803 (Build 17134.1792)
Oracle jdk1.8.0_191

Sorry for unnecessarily bothering.
