### ISSUE TITLE
JasperReports library fails when using Google fonts in custom visualization element rendered with chromium

### ISSUE THREAD

**Issue by dhombios** [TIBCOSoftware/jasperreports#197]
When using Google fonts in a custom visulization element rendered with chromium, the following exception is raised:
```
net.sf.jasperreports.engine.JRRuntimeException: java.util.concurrent.ExecutionException: net.sf.jasperreports.engine.JRRuntimeException: Script failed: Uncaught (in promise)
net.sf.jasperreports.engine.JRRuntimeException: java.util.concurrent.ExecutionException: net.sf.jasperreports.engine.JRRuntimeException: Script failed: Uncaught (in promise)
        at net.sf.jasperreports.chrome.BrowserService.lambda$evaluateInPage$1(BrowserService.java:149)
        at net.sf.jasperreports.chrome.StandardPageCreator.lambda$runInPage$0(StandardPageCreator.java:65)
        at net.sf.jasperreports.chrome.ChromeInstance.runWithChromeInstance(ChromeInstance.java:92)
        at net.sf.jasperreports.chrome.StandardPageCreator.runInPage(StandardPageCreator.java:52)
        at net.sf.jasperreports.chrome.BrowserService.evaluateInPage(BrowserService.java:98)
        at net.sf.jasperreports.customvisualization.export.ChromeCVElementImageDataProvider.getImageData(ChromeCVElementImageDataProvider.java:134)
        at net.sf.jasperreports.customvisualization.export.CVElementDefaultImageDataProvider.getImageData(CVElementDefaultImageDataProvider.java:56)
        at net.sf.jasperreports.customvisualization.export.CVElementImageProvider.createRenderable(CVElementImageProvider.java:134)
        at net.sf.jasperreports.customvisualization.export.CVElementImageProvider.getImage(CVElementImageProvider.java:86)
        at net.sf.jasperreports.customvisualization.export.CVElementPdfHandler.exportElement(CVElementPdfHandler.java:58)
        at net.sf.jasperreports.engine.export.JRPdfExporter.exportGenericElement(JRPdfExporter.java:4141)
        at net.sf.jasperreports.engine.export.JRPdfExporter.exportElements(JRPdfExporter.java:1290)
        at net.sf.jasperreports.engine.export.JRPdfExporter.exportPage(JRPdfExporter.java:1210)
        at net.sf.jasperreports.engine.export.JRPdfExporter.exportReportToStream(JRPdfExporter.java:1074)
        at net.sf.jasperreports.engine.export.JRPdfExporter.exportReport(JRPdfExporter.java:691)
        at net.sf.jasperreports.engine.JasperExportManager.exportToPdfFile(JasperExportManager.java:155)
        at net.sf.jasperreports.engine.JasperExportManager.exportReportToPdfFile(JasperExportManager.java:503)
        at com.Dhom.MyReport.Report_generator.publish(Report_generator.java:83)
        at com.Dhom.MyReport.CLI.main(CLI.java:120)
Caused by: java.util.concurrent.ExecutionException: net.sf.jasperreports.engine.JRRuntimeException: Script failed: Uncaught (in promise)
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
        at net.sf.jasperreports.chrome.BrowserService.lambda$evaluateInPage$1(BrowserService.java:144)
        ... 18 more
Caused by: net.sf.jasperreports.engine.JRRuntimeException: Script failed: Uncaught (in promise)
        at net.sf.jasperreports.chrome.ChromePage.checkException(ChromePage.java:95)
        at net.sf.jasperreports.chrome.ChromePage.evaluatePromise(ChromePage.java:67)
        at net.sf.jasperreports.customvisualization.export.ChromeCVElementImageDataProvider.lambda$getImageData$0(ChromeCVElementImageDataProvider.java:135)
        at net.sf.jasperreports.chrome.BrowserService.lambda$null$0(BrowserService.java:121)
        at com.github.kklisura.cdt.services.impl.ChromeDevToolsServiceImpl.lambda$handleEvent$1(ChromeDevToolsServiceImpl.java:306)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

On the other hand PhantomJs, cannot be used as Google fonts api provides them in woff2, which is unsupported, and it is not able to use font files provided as a jar generated with Jasper Studio.

Is there any workaround to provide custom fonts to any of the available CVC renderers (PhantomJs or Chrome) without installing them?

Thanks in advance

**CSS:** 
```
@charset "UTF-8";

@import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Syncopate:wght@400;700&display=swap');

.num-text {
    fill: white;
    font-family: 'Montserrat', sans-serif;
}
```

**Comment by teodord** [comment]
Please provide some files so that we can reproduce this problem.

**Comment by teodord** [comment]
Anything new on this one? Feel free to reopen if you can provide more details about it.

Thank you,
Teodor
