### ISSUE TITLE
NPE for staticText element

### ISSUE THREAD

**Issue by oflege** [TIBCOSoftware/jasperreports#20]
I am using v6.5.1 and have a report with a band that contains a single chart and and a static text like this:
`<staticText>
  <reportElement style="section title" x="11" y="30" width="520" height="20" uuid="5aec9479-4c72-487d-a216-6e19336ab97b"/>
  <text><![CDATA[Performance]]></text>
</staticText>`

Whenever that band does not fit on the current page and is moved to the next page, the refill of the static text runs into a NPE (see below). The problem seems to be caused by JRFillTextElement#rewind, in which rawText is set to the value of oldRawText, which is null. Judging from the constructors of JRFillStaticText, rawText is never supposed to be null.

The report renders just fine with net.sf.jasperreports.legacy.band.evaluation.enabled=true 

`java.lang.NullPointerException: null
	at net.sf.jasperreports.engine.fill.JRFillTextElement.setPrintText(JRFillTextElement.java:1057)
	at net.sf.jasperreports.engine.fill.JRFillStaticText.fill(JRFillStaticText.java:215)
	at net.sf.jasperreports.engine.fill.JRFillElementContainer.fillElements(JRFillElementContainer.java:1039)
	at net.sf.jasperreports.engine.fill.JRFillBand.fill(JRFillBand.java:454)
	at net.sf.jasperreports.engine.fill.JRFillBand.fill(JRFillBand.java:413)
	at net.sf.jasperreports.engine.fill.JRFillBand.refill(JRFillBand.java:385)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillColumnBand(JRVerticalFiller.java:2608)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillDetail(JRVerticalFiller.java:791)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReportStart(JRVerticalFiller.java:252)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:99)
	at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:609)
	at net.sf.jasperreports.engine.fill.BaseReportFiller.fill(BaseReportFiller.java:405)
	at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:140)
	at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:667)
	at net.sf.jasperreports.engine.JasperRunManager.runToPdf(JasperRunManager.java:493)
	at net.sf.jasperreports.engine.JasperRunManager.runReportToPdf(JasperRunManager.java:896)`

**Comment by dadza** [comment]
For the records this is probably the same problem as the one reported at https://community.jaspersoft.com/jasperreports-library/issues/10486
