### ISSUE TITLE
upgrade POI compile dependency to 5.0.0 for fixing java.lang.NoSuchMethodError: org.apache.poi.hssf.usermodel.HSSFFont.getIndex()S

### ISSUE THREAD

**Issue by neowcng** [TIBCOSoftware/jasperreports#210]
we have an old jasperreports requiring to export the output in XLS (not XLSX) format
now our webapp project required to upgrade POI 5.0.0 to access certain features and bug fix

after the POI upgrade, the report no longer generated due to this error
java.lang.NoSuchMethodError: org.apache.poi.hssf.usermodel.HSSFFont.getIndex()S

checking the POI source code, it seems at POI 5.0.0 the HSSFFont.getIndex() function has changed the return type
so the jasperreports lib no longer found such method in the XLS exporter to trigger this error

POI v4.1.2
[https://github.com/apache/poi/blob/REL_4_1_2/src/java/org/apache/poi/hssf/usermodel/HSSFFont.java#L90](url)

POI v5.0.0
[https://github.com/apache/poi/blob/REL_5_0_0/src/java/org/apache/poi/hssf/usermodel/HSSFFont.java#L85](url)

a dependency upgrade on jasperreports lib and recompilation should be able to solve this problem
please bump the dependency

original stack trace below

Caused by: java.lang.NoSuchMethodError: org.apache.poi.hssf.usermodel.HSSFFont.getIndex()S
at net.sf.jasperreports.engine.export.JRXlsExporter$StyleInfo.computeHash(JRXlsExporter.java:2672) ~[jasperreports-6.12.2.jar:6.12.2-75c5e90a222ab406e416cbf590a5397028a52de3]
at net.sf.jasperreports.engine.export.JRXlsExporter$StyleInfo.<init>(JRXlsExporter.java:2662) ~[jasperreports-6.12.2.jar:6.12.2-75c5e90a222ab406e416cbf590a5397028a52de3]
at net.sf.jasperreports.engine.export.JRXlsExporter$StyleInfo.<init>(JRXlsExporter.java:2623) ~[jasperreports-6.12.2.jar:6.12.2-75c5e90a222ab406e416cbf590a5397028a52de3]
at net.sf.jasperreports.engine.export.JRXlsExporter.getLoadedCellStyle(JRXlsExporter.java:1425) ~[jasperreports-6.12.2.jar:6.12.2-75c5e90a222ab406e416cbf590a5397028a52de3]
at net.sf.jasperreports.engine.export.JRXlsExporter.addBlankCell(JRXlsExporter.java:723) ~[jasperreports-6.12.2.jar:6.12.2-75c5e90a222ab406e416cbf590a5397028a52de3]
at net.sf.jasperreports.engine.export.JRXlsAbstractExporter.exportPage(JRXlsAbstractExporter.java:1278) ~[jasperreports-6.12.2.jar:6.12.2-75c5e90a222ab406e416cbf590a5397028a52de3]
at net.sf.jasperreports.engine.export.JRXlsAbstractExporter.exportReportToStream(JRXlsAbstractExporter.java:1031) ~[jasperreports-6.12.2.jar:6.12.2-75c5e90a222ab406e416cbf590a5397028a52de3]
at net.sf.jasperreports.engine.export.JRXlsAbstractExporter.exportReport(JRXlsAbstractExporter.java:879) ~[jasperreports-6.12.2.jar:6.12.2-75c5e90a222ab406e416cbf590a5397028a52de3]
.......... skipping the spring webmvc /framework and jboss eap server stacktrace below

**Comment by neowcng** [comment]
i tried to updated pom.xml and try mvn:package at my local PC

```
diff --git a/jasperreports/pom.xml b/jasperreports/pom.xml
index bf5543723..67a3c55ce 100644
--- a/jasperreports/pom.xml
+++ b/jasperreports/pom.xml
@@ -150,16 +150,28 @@
                <dependency>
                        <groupId>org.apache.poi</groupId>
                        <artifactId>poi</artifactId>
-                       <version>4.1.1</version>
+                       <version>5.0.0</version>
                        <scope>compile</scope>
                        <optional>true</optional>
+                       <exclusions>
+                               <exclusion>
+                                       <groupId>org.slf4j</groupId>
+                                       <artifactId>jcl-over-slf4j</artifactId>
+                               </exclusion>
+                       </exclusions>
                </dependency>
                <dependency>
                        <groupId>org.apache.poi</groupId>
                        <artifactId>poi-ooxml</artifactId>
-                       <version>4.1.1</version>
+                       <version>5.0.0</version>
                        <scope>compile</scope>
                        <optional>true</optional>
+                       <exclusions>
+                               <exclusion>
+                                       <groupId>org.apache.xmlgraphics</groupId>
+                                       <artifactId>batik-all</artifactId>
+                               </exclusion>
+                       </exclusions>
                </dependency>
                <dependency>
                        <groupId>javax.servlet</groupId>
```

**Comment by Sheshasr** [comment]
Do we have a compiled library available for Product usage? I could see 6.18 latest available also has same issue.

**Comment by teodord** [comment]
This commit will be part of the next release, in a few weeks from now.

Thank you,
Teodor

**Comment by teodord** [comment]
As the commit indicates, we upgraded to 5.1.0.

Thanks,
Teodor

**Comment by ieu68667** [comment]
@teodord do u know when the next release will be? The old POI lib 4.0.1 got vulnerability of log4j, which we could not use any more. So we would rely on this coming new version.
