### ISSUE TITLE
Spring fix.

### ISSUE THREAD

**Issue by springzen** [TIBCOSoftware/jasperreports#22]
Spring support is broken. <ref local is no longer supported by spring schema - you must use <ref bean instead.
Since I cannot create a pull request, I have attached the fixes to this issue.

Cheers,
/.Springzen

[SpringFix.zip](https://github.com/TIBCOSoftware/jasperreports/files/1888334/SpringFix.zip)

**Comment by mirkoliver** [comment]
An example for this:

Using Spring 5.0.3 together with JasperReports 6.5.1 and executing this code ...

```
MyBean b = new MyBean();
List<MyBean> l = new ArrayList<>();
l.add(b);
 
String s = JasperFillManager.fillReportToFile("C:/PDF.jasper", 
                      new HashMap<String, Object>(), new JRBeanCollectionDataSource(l));
```
... results in the Exception:

```
org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 11 in XML document from URL [jar:file:/C:/EclipseWorkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp6/wtpwebapps/myapp/WEB-INF/lib/jasperreports-chart-themes-6.5.1.jar!/net/sf/jasperreports/chartthemes/spring/beans/chartThemesBeans.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 11; columnNumber: 38; cvc-complex-type.3.2.2: Attribut 'local' darf nicht in Element 'ref' vorkommen.
    at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:398) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
    at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:335) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
    at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:303) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
    at net.sf.jasperreports.extensions.SpringExtensionsRegistryFactory.getBeanFactory(SpringExtensionsRegistryFactory.java:111) ~[jasperreports-6.5.1.jar:6.5.1]
    at net.sf.jasperreports.extensions.SpringExtensionsRegistryFactory.createRegistry(SpringExtensionsRegistryFactory.java:76) ~[jasperreports-6.5.1.jar:6.5.1]
    at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.instantiateRegistry(DefaultExtensionsRegistry.java:295) ~[jasperreports-6.5.1.jar:6.5.1]
    at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.loadRegistries(DefaultExtensionsRegistry.java:270) ~[jasperreports-6.5.1.jar:6.5.1]
    at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.loadRegistries(DefaultExtensionsRegistry.java:190) [jasperreports-6.5.1.jar:6.5.1]
    at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.getRegistries(DefaultExtensionsRegistry.java:153) [jasperreports-6.5.1.jar:6.5.1]
    at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.getExtensions(DefaultExtensionsRegistry.java:125) [jasperreports-6.5.1.jar:6.5.1]
    at net.sf.jasperreports.engine.util.JRStyledTextParser.<clinit>(JRStyledTextParser.java:86) [jasperreports-6.5.1.jar:6.5.1]
    at net.sf.jasperreports.engine.fill.JRBaseFiller.<init>(JRBaseFiller.java:111) [jasperreports-6.5.1.jar:6.5.1]
    at net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(JRVerticalFiller.java:69) [jasperreports-6.5.1.jar:6.5.1]
    at net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(JRVerticalFiller.java:57) [jasperreports-6.5.1.jar:6.5.1]
    at net.sf.jasperreports.engine.fill.JRFiller.createBandReportFiller(JRFiller.java:219) [jasperreports-6.5.1.jar:6.5.1]
    at net.sf.jasperreports.engine.fill.JRFiller.createReportFiller(JRFiller.java:234) [jasperreports-6.5.1.jar:6.5.1]
    at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:134) [jasperreports-6.5.1.jar:6.5.1]
    at net.sf.jasperreports.engine.JasperFillManager.fillToFile(JasperFillManager.java:504) [jasperreports-6.5.1.jar:6.5.1]
    at net.sf.jasperreports.engine.JasperFillManager.fillReportToFile(JasperFillManager.java:888) [jasperreports-6.5.1.jar:6.5.1]
```

**Comment by mirkoliver** [comment]
By the way - great solution for this bug - @springzen - this works!
