### ISSUE TITLE
Interrupted while locking virtualization context

### ISSUE THREAD

**Issue by SATISHEEEK** [TIBCOSoftware/jasperreports#223]
Dear JasperReports devs,
I have been using your library in my projects for a long time, but now I am facing a very unique issue. 

We're generating a report with a huge dataset and semi-difficult report design. (Design itself isn't complicated, but it's made of 10 subreports). 
We're using SwapFile virtualizer that works fine. 

But on Openshift environment for XLS output we're getting the following error: 

```
net.sf.jasperreports.engine.JRRuntimeException: Interrupted while locking virtualization context. 	 
	at net.sf.jasperreports.engine.fill.JRVirtualizationContext.lock(JRVirtualizationContext.java:616) 
	at net.sf.jasperreports.engine.base.ElementsBlock.lockContext(ElementsBlock.java:112) 
	at net.sf.jasperreports.engine.base.ElementsBlock.get(ElementsBlock.java:157) 
	at net.sf.jasperreports.engine.base.VirtualizableElementList.get(VirtualizableElementList.java:95) 
	at net.sf.jasperreports.engine.base.VirtualizableElementList.get(VirtualizableElementList.java:42) 
	at net.sf.jasperreports.engine.export.JRGridLayout.getElement(JRGridLayout.java:197) 
	at net.sf.jasperreports.engine.export.JRGridLayout.getElement(JRGridLayout.java:201) 
	at net.sf.jasperreports.engine.export.JRGridLayout.getElement(JRGridLayout.java:201) 
	at net.sf.jasperreports.engine.export.JRGridLayout.getElement(JRGridLayout.java:201) 
	at net.sf.jasperreports.engine.export.ElementGridCell.getElement(ElementGridCell.java:83) 
	at net.sf.jasperreports.engine.export.JRXlsAbstractExporter.exportPage(JRXlsAbstractExporter.java:1183) 
	at net.sf.jasperreports.engine.export.JRXlsAbstractExporter.exportReportToStream(JRXlsAbstractExporter.java:1031) 
	at net.sf.jasperreports.engine.export.JRXlsAbstractExporter.exportReport(JRXlsAbstractExporter.java:879)
``` 
**Some details to this issue:**
- PDF output works fine, its happening only for excel
- Swapfile has almost 200 MB's, final XLS file has 104 MB
- Code works on our docker dev machines but crashes in OS env
- The lock is always interrupted after 15 minutes exactly. 

There is only 1 relevant source on google 
 - https://stackoverflow.com/questions/37172323/jasperreport-interrupted-while-locking-virtualization-context 
 - which is not working for our usecase. 

Virtualizer & Swapfile settings: 
- JRSwapFileVirtualizer(100, swapFile, true);
- JRSwapFile(System.getProperty("java.io.tmpdir"), 4096, 2048);

..I was able to find this FIXME comment in the method that produces the exception
https://github.com/TIBCOSoftware/jasperreports/blob/6.11.0/jasperreports/src/net/sf/jasperreports/engine/base/ElementsBlock.java : 102

We tried almost everything already. From the openshift configuration, to report design changes and we're slowly running out of ideas.

Do you, please, have any experience with this kind of issue? 
Used library: 6.11.0 (We tried the newest version and didn't work either) 

@teodord @dadza @shertage  @mnarcis 
Thank you for any kind of information.

Kind Regards,
Jan

**Comment by SATISHEEEK** [comment]
Hi All,
we figured out, that the error is probably not code-related. 
But some configuration is killing our report-thread after 15 minutes. We suspected http://jasperreports.sourceforge.net/api/net/sf/jasperreports/chrome/Chrome.html#PROPERTY_IDLE_TIMEOUT ,
but changing it doesn't make difference...

Anyone from your team with some ideas?

Thanks in advance.
