### ISSUE TITLE
Jaspersoft Studio 6.13.0 cannot open after update to 6.17.0

### ISSUE THREAD

**Issue by AdeSupriyadi** [TIBCOSoftware/jasperreports#228]
I was Install Jaspersoft studio commuty edition ver. 6.13.0 then I click Help>check update
There is update 6.17.0 then I update it.
After Update Jaspersoft studio can't start.

Splash Image still showing ver 6.13.0
![image](https://user-images.githubusercontent.com/14267724/139698912-8fb2e1fe-c742-4713-8bea-4e8806f79969.png)
After that showing error:
![image](https://user-images.githubusercontent.com/14267724/139699045-5d8aefff-d526-4421-81fe-9db0cd2649da.png)

At bottom of log:
```log
!ENTRY org.eclipse.osgi 4 0 2021-11-01 22:39:40.217
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "com.jaspersoft.studio.rcp.application" could not be found in the registry. The applications available are: org.eclipse.ant.core.antRunner, org.eclipse.e4.ui.workbench.swt.E4Application, org.eclipse.e4.ui.workbench.swt.GenTopic, org.eclipse.equinox.app.error, org.eclipse.equinox.p2.garbagecollector.application, org.eclipse.equinox.p2.touchpoint.natives.nativePackageExtractor, org.eclipse.help.base.infocenterApplication, org.eclipse.help.base.helpApplication, org.eclipse.help.base.indexTool, org.eclipse.jdt.core.JavaCodeFormatter, org.eclipse.jdt.core.JavaIndexer.
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:252)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:33)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

Environment:
- OS: Ubuntu 20.04
- Java:
```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

**Comment by teodord** [comment]
This is a Jaspersoft Studio issue and not a JasperReports Library issue, so you should post it here:
https://github.com/TIBCOSoftware/jaspersoft-studio-ce/issues

I suggest you simply uninstall version 6.13.0 and install version 6.17.0 using the normal installer, avoiding the in-app upgrade, which is probably causing the issue.
