### ISSUE TITLE
Setting escapeFormula to true for CSV injection fix results in StringIndexOutOfBoundsException in case the CSV value is empty

### ISSUE THREAD

**Issue by asookazian** [TIBCOSoftware/jasperreports#229]
Tested 6.18.1 JRL with our custom report manager application and the fix for CSV injection works (deactivated hyperlink in my test case when csv file opened in Excel by prepending with a space) however there is a bug when the value for CSV cell is empty string (blank).

Sample stack trace:

```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
    at java.lang.String.charAt(String.java:658)[:1.8.0_281]
    at net.sf.jasperreports.engine.export.JRAbstractCsvExporter.prepareText(JRAbstractCsvExporter.java:241)[424:com.nextgate.reporter.ngrs-reporter-service:11.2.0.SNAPSHOT]
    at net.sf.jasperreports.engine.export.JRCsvExporter.exportPage(JRCsvExporter.java:220)[424:com.nextgate.reporter.ngrs-reporter-service:11.2.0.SNAPSHOT]
    at net.sf.jasperreports.engine.export.JRAbstractCsvExporter.exportReportToWriter(JRAbstractCsvExporter.java:180)[424:com.nextgate.reporter.ngrs-reporter-service:11.2.0.SNAPSHOT]
    at net.sf.jasperreports.engine.export.JRAbstractCsvExporter.exportReport(JRAbstractCsvExporter.java:121)[424:com.nextgate.reporter.ngrs-reporter-service:11.2.0.SNAPSHOT]
    at com.nextgate.reporter.reportmanager.ReportManager.fillReport(ReportManager.java:995)[424:com.nextgate.reporter.ngrs-reporter-service:11.2.0.SNAPSHOT]
    at com.nextgate.reporter.reportmanager.ReportManager.generateReportCsv(ReportManager.java:709)[424:com.nextgate.reporter.ngrs-reporter-service:11.2.0.SNAPSHOT]
    at com.nextgate.reporter.impls.ReporterServiceImpl.getGenerateReport(ReporterServiceImpl.java:412)[424:com.nextgate.reporter.ngrs-reporter-service:11.2.0.SNAPSHOT]
```

Code used in our app's CSV report generation API to affect CSV protection:

```
SimpleCsvExporterConfiguration configuration = new SimpleCsvExporterConfiguration();
configuration.setEscapeFormula(true);
csvExporter.setConfiguration(configuration);
csvExporter.exportReport();
```

The JRL fix for CSV injection is in this method: net.sf.jasperreports.engine.export.JRAbstractCsvExporter.prepareText(String):

```
if (escapeFormula && ESCAPE_FORMULA_CHARACTERS.indexOf(str.charAt(0)) >= 0)
{
   str = " " + str;
}
```
where ESCAPE_FORMULA_CHARACTERS = "=+-@";

The fix is a simple null check and str.isEmpty() check prior to processing with the empty space prefixing.  If the str instance is null or empty, then there is no need to prefix with space.

**Comment by asookazian** [comment]
Fix applied on 6.18.1 branch local checkout.  Behavior does not reproduce after deploying fix locally with our app (fixed).  Test case uses hyperlink in one field of detail band and empty value in another field of detail band.  Hyperlink is successfully deactivated and StringIndexOutOfBoundsException does not reproduce.

Pls advise and I can attempt to push changes upstream via pull request.

```
if (escapeFormula && !str.isEmpty() && ESCAPE_FORMULA_CHARACTERS.indexOf(str.charAt(0)) >= 0)
{
    str = " " + str;
}
```
