### ISSUE TITLE
NoSuchMethodError: java.lang.Math.floorDiv when calling DAYS function.

### ISSUE THREAD

**Issue by greleuniforme** [TIBCOSoftware/jasperreports#286]
When I'm calling the jasper DAYS function with two non-null parameters i'm getting an error with the math.floordiv function:

java.lang.NoSuchMethodError: java.lang.Math.floorDiv(JI)J
	at net.sf.jasperreports.functions.standard.DateTimeFunctions.ofInstant(DateTimeFunctions.java:750)
	at net.sf.jasperreports.functions.standard.DateTimeFunctions.DAYS(DateTimeFunctions.java:395)
	at detailResident_1658737979121_291836.DAYS(detailResident_1658737979121_291836:355)
	at detailResident_1658737979121_291836.evaluate(detailResident_1658737979121_291836:127)
	at net.sf.jasperreports.engine.fill.JREvaluator.evaluate(JREvaluator.java:313)
	at net.sf.jasperreports.engine.fill.JRCalculator.evaluate(JRCalculator.java:673)
	at net.sf.jasperreports.engine.fill.JRCalculator.evaluate(JRCalculator.java:641)
	at net.sf.jasperreports.engine.fill.JRFillElement.evaluateExpression(JRFillElement.java:1175)
	at net.sf.jasperreports.engine.fill.JRFillTextField.evaluateText(JRFillTextField.java:555)
	at net.sf.jasperreports.engine.fill.JRFillTextField.evaluate(JRFillTextField.java:540)
	at net.sf.jasperreports.engine.fill.JRFillElementContainer.evaluate(JRFillElementContainer.java:383)
	at net.sf.jasperreports.engine.fill.JRFillBand.evaluate(JRFillBand.java:548)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillColumnBand(JRVerticalFiller.java:2613)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillDetail(JRVerticalFiller.java:836)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReportStart(JRVerticalFiller.java:275)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:119)
	at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:622)
	at net.sf.jasperreports.engine.fill.BaseReportFiller.fill(BaseReportFiller.java:414)
	at net.sf.jasperreports.engine.fill.JRFillSubreport.fillSubreport(JRFillSubreport.java:826)
	at net.sf.jasperreports.engine.fill.JRSubreportRunnable.run(JRSubreportRunnable.java:61)
	at net.sf.jasperreports.engine.fill.AbstractThreadSubreportRunner.run(AbstractThreadSubreportRunner.java:221)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by dadza** [comment]
You can fetch the latest snapshot (jasperreports-functions-master-20220729.073102-12.jar) from [the JFrog repository](https://jaspersoft.jfrog.io/ui/native/jr-ce-snapshots/net/sf/jasperreports/jasperreports-functions/master-SNAPSHOT/)
