### ISSUE TITLE
Inconsistent XPath parameters when creating Dataset in Jasperreport 6.20.1

### ISSUE THREAD

**Issue by matchman72** [TIBCOSoftware/jasperreports#346]
![image](https://user-images.githubusercontent.com/11850034/233333492-8ae7d3b8-d4fa-495a-9983-9886b1c6d94a.png)

We have reports which set XML_FILE, XML_INPUT_STREAM and net.sf.jasperreports.xml.source values when displaying List and Tables. When we compile these reports by Jasperreport 6.20.1 by

```
JasperCompileManager.compileReportToFile(inputJrxmlFile, outputJasperFile);
```

It shows errors

```
(ServerService Thread Pool -- 95) Report design not valid : 
	 1. Parameter not found : XML_FILE
	 2. Parameter not found : net.sf.jasperreports.xml.source
	 3. Unknown parameter XML_FILE in dataset Dataset1.
	 4. Unknown parameter net.sf.jasperreports.xml.source in dataset Dataset1.: net.sf.jasperreports.engine.design.JRValidationException: Report design not valid : 
	 1. Parameter not found : XML_FILE
	 2. Parameter not found : net.sf.jasperreports.xml.source
	 3. Unknown parameter XML_FILE in dataset Dataset1.
	 4. Unknown parameter net.sf.jasperreports.xml.source in dataset Dataset1.
	at deployment.report.war//net.sf.jasperreports.engine.design.JRAbstractCompiler.verifyDesign(JRAbstractCompiler.java:316)
	at deployment.report.war//net.sf.jasperreports.engine.design.JRAbstractCompiler.compileReport(JRAbstractCompiler.java:175)
	at deployment.report.war//net.sf.jasperreports.engine.JasperCompileManager.compile(JasperCompileManager.java:358)
	at deployment.report.war//net.sf.jasperreports.engine.JasperCompileManager.compileToFile(JasperCompileManager.java:274)
	at deployment.report.war//net.sf.jasperreports.engine.JasperCompileManager.compileToFile(JasperCompileManager.java:256)
	at deployment.report.war//net.sf.jasperreports.engine.JasperCompileManager.compileReportToFile(JasperCompileManager.java:555)
```

**Comment by matchman72** [comment]
6.20.0 => compile ok
6.20.1 =>
```
net.sf.jasperreports.engine.design.JRValidationException: Report design not valid : 
	 1. Unknown parameter net.sf.jasperreports.xml.source in dataset Dataset1.
	at net.sf.jasperreports.engine.design.JRAbstractCompiler.verifyDesign(JRAbstractCompiler.java:316)
	at net.sf.jasperreports.engine.design.JRAbstractCompiler.compileReport(JRAbstractCompiler.java:175)
	at net.sf.jasperreports.engine.JasperCompileManager.compile(JasperCompileManager.java:358)
	at net.sf.jasperreports.engine.JasperCompileManager.compileToFile(JasperCompileManager.java:274)
	at net.sf.jasperreports.engine.JasperCompileManager.compileToFile(JasperCompileManager.java:256)
	at net.sf.jasperreports.engine.JasperCompileManager.compileReportToFile(JasperCompileManager.java:555)
	at CompileJrxml.compile(CompileJrxml.java:14)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)


```

[sample.zip](https://github.com/TIBCOSoftware/jasperreports/files/11287257/sample.zip)
