### ISSUE TITLE
NullPointerException when using JsonExporter

### ISSUE THREAD

**Issue by heyizhiyuan** [TIBCOSoftware/jasperreports#360]
My code：
```java
JsonExporter exporter = new JsonExporter();
exporter.setExporterInput(new SimpleExporterInput(jasperPrint));
SimpleJsonReportConfiguration configuration = new SimpleJsonReportConfiguration();
exporter.setConfiguration(configuration);
JsonExporterOutput outPut = new SimpleJsonExporterOutput(out);
exporter.setExporterOutput(outPut);
exporter.setReportContext(new SimpleReportContext());
exporter.exportReport();
out.flush();
```

Exception message:

java.lang.NullPointerException: null
	at net.sf.jasperreports.components.table.util.TableUtil.getAllColumns(TableUtil.java:162)
	at net.sf.jasperreports.components.headertoolbar.json.HeaderToolbarElementJsonHandler.getColumnGroupsData(HeaderToolbarElementJsonHandler.java:807)
	at net.sf.jasperreports.components.headertoolbar.json.HeaderToolbarElementJsonHandler.getJsonFragment(HeaderToolbarElementJsonHandler.java:233)
	at net.sf.jasperreports.engine.export.JsonExporter.exportGenericElement(JsonExporter.java:519)
	at net.sf.jasperreports.engine.export.JsonExporter.exportElements(JsonExporter.java:285)
	at net.sf.jasperreports.engine.export.JsonExporter.exportFrame(JsonExporter.java:294)
	at net.sf.jasperreports.engine.export.JsonExporter.exportElements(JsonExporter.java:281)
	at net.sf.jasperreports.engine.export.JsonExporter.exportFrame(JsonExporter.java:294)
	at net.sf.jasperreports.engine.export.JsonExporter.exportElements(JsonExporter.java:281)
	at net.sf.jasperreports.engine.export.JsonExporter.exportPage(JsonExporter.java:254)
	at net.sf.jasperreports.engine.export.JsonExporter.exportReportToWriter(JsonExporter.java:221)
	at net.sf.jasperreports.engine.export.JsonExporter.exportReport(JsonExporter.java:163)

**Comment by teodord** [comment]
If you can provide more details about what you are trying to achieve, feel free to reopen this.

Thank you,
Teodor
