### ISSUE TITLE
Issue upgrading from 6.17.0 to 6.20.6

### ISSUE THREAD

**Issue by DannyOcean04** [TIBCOSoftware/jasperreports#399]
So my current project is a Java 8 web-app, and we are using JasperReport 6.17.0 and itext-2.1.7.js8. I tried to upgrade to the most recent version of JasperReport 6.20.6 and OpenPDF 1.3.32, I've also updated the JasperReport Dependencies like jackson-core.
However whenever I'd run the method to create and export the pdf file I'd receive this error:

`java.lang.NoSuchMethodError: com.lowagie.text.Phrase.add(Lcom/lowagie/text/Element;)Z
		at net.sf.jasperreports.export.pdf.classic.ClassicPhrase.add(ClassicPhrase.java:56)
		at net.sf.jasperreports.engine.export.JRPdfExporter.getPhrase(JRPdfExporter.java:2257)
		at net.sf.jasperreports.engine.export.PdfTextRenderer.draw(PdfTextRenderer.java:94)
		at net.sf.jasperreports.engine.export.AbstractTextRenderer.renderParagraph(AbstractTextRenderer.java:719)
		at net.sf.jasperreports.engine.export.AbstractPdfTextRenderer.renderParagraph(AbstractPdfTextRenderer.java:169)
		at net.sf.jasperreports.engine.export.AbstractTextRenderer.render(AbstractTextRenderer.java:389)
		at net.sf.jasperreports.engine.export.JRPdfExporter.exportText(JRPdfExporter.java:2539)
		at net.sf.jasperreports.engine.export.JRPdfExporter.exportElements(JRPdfExporter.java:1282)
		at net.sf.jasperreports.engine.export.JRPdfExporter.exportFrame(JRPdfExporter.java:3381)
		at net.sf.jasperreports.engine.export.JRPdfExporter.exportElements(JRPdfExporter.java:1287)
		at net.sf.jasperreports.engine.export.JRPdfExporter.exportFrame(JRPdfExporter.java:3381)
		at net.sf.jasperreports.engine.export.JRPdfExporter.exportElements(JRPdfExporter.java:1287)
		at net.sf.jasperreports.engine.export.JRPdfExporter.exportPage(JRPdfExporter.java:1219)
		at net.sf.jasperreports.engine.export.JRPdfExporter.exportReportToStream(JRPdfExporter.java:1112)
		at net.sf.jasperreports.engine.export.JRPdfExporter.exportReport(JRPdfExporter.java:677)`

I have read a previous issue back in July of a user having a similar issue/error. The solution he had was to remove the iText/iTextPDF libraries as they may affect the OpenPDF library, However even after removing the iText/iTextPDF jar files from the library, I was still receiving the same error message.

I've tried changing the JasperReport versions and the OpenPDF versions however every JasperReport version after the switch from iText is causing this error message. I was wondering if anyone had experienced something similar or has noticed that I'm missing a step in installing these jar libraries to my project.

Thanks!

**Comment by dadza** [comment]
My suggestion is to confirm that iText is no longer present on your application's classpath, I can't think of any other explanation for the error at this moment.

Can you include a line like this somewhere in your code, and verify the jar in the printed URL?  (Feel free to use any logging framework that you have instead of System.out)

`System.out.println(net.sf.jasperreports.export.pdf.classic.ClassicPhrase.class.getResource("/com/lowagie/text/Phrase.class"));`

Regards,
Lucian

**Comment by DannyOcean04** [comment]
Hey Lucian,

Thanks for the help, I was able to find the iText jar file hidden within a Global Library. I've now tested it with a modified version of the Global Library without the iText Jar file and it all seems to be working fine now.

Regards,
Dan
