### ISSUE TITLE
Error in JRXmlLoader after migrating to java 17 and Spring Boot 3

### ISSUE THREAD

**Issue by ngallion** [TIBCOSoftware/jasperreports#425]
We are working on migrating our document generation service to Spring Boot 3 and java 17, and we are now encountering the following error when trying to load XML:

```
net.sf.jasperreports.engine.JRRuntimeException: Could not instantiate class com.sun.org.apache.xerces.internal.util.XMLGrammarPoolImpl.
	at net.sf.jasperreports.engine.util.ClassUtils.instantiateClass(ClassUtils.java:81) ~[jasperreports-6.21.0.jar:6.21.0-4f56c4f36cd19e17675219a9ac4692d5f0f13b06]
	at net.sf.jasperreports.engine.xml.BaseSaxParserFactory.setGrammarPoolProperty(BaseSaxParserFactory.java:229) ~[jasperreports-6.21.0.jar:6.21.0-4f56c4f36cd19e17675219a9ac4692d5f0f13b06]
	at net.sf.jasperreports.engine.xml.BaseSaxParserFactory.enableSchemaCaching(BaseSaxParserFactory.java:192) ~[jasperreports-6.21.0.jar:6.21.0-4f56c4f36cd19e17675219a9ac4692d5f0f13b06]
	at net.sf.jasperreports.engine.xml.BaseSaxParserFactory.configureParser(BaseSaxParserFactory.java:164) ~[jasperreports-6.21.0.jar:6.21.0-4f56c4f36cd19e17675219a9ac4692d5f0f13b06]
	at net.sf.jasperreports.engine.xml.BaseSaxParserFactory.createParser(BaseSaxParserFactory.java:118) ~[jasperreports-6.21.0.jar:6.21.0-4f56c4f36cd19e17675219a9ac4692d5f0f13b06]
	at net.sf.jasperreports.engine.xml.JRXmlDigesterFactory.createParser(JRXmlDigesterFactory.java:1569) ~[jasperreports-6.21.0.jar:6.21.0-4f56c4f36cd19e17675219a9ac4692d5f0f13b06]
	at net.sf.jasperreports.engine.xml.JRXmlDigesterFactory.createDigester(JRXmlDigesterFactory.java:1547) ~[jasperreports-6.21.0.jar:6.21.0-4f56c4f36cd19e17675219a9ac4692d5f0f13b06]
	at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:250) ~[jasperreports-6.21.0.jar:6.21.0-4f56c4f36cd19e17675219a9ac4692d5f0f13b06]
	at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:235) ~[jasperreports-6.21.0.jar:6.21.0-4f56c4f36cd19e17675219a9ac4692d5f0f13b06]
```

There were changes to encapsulation with java 17, but adding `--add-opens java.base/java.lang=ALL-UNNAMED` as a VM option does not fix - for other libraries with issues like this, opening unnamed classes seems to fix the issues.

Any insight into what may be causing this error and what we can do to fix?

**Comment by dadza** [comment]
As a note, the error is not blocking and loading the report proceeds without schema caching (and the error is printed only when debug logging is enabled for net.sf.jasperreports.engine.xml.BaseSaxParserFactory).

If you want to fix it you need to run Java with `--add-exports java.xml/com.sun.org.apache.xerces.internal.util=ALL-UNNAMED`

Alternative ways to avoid the error:
- add an Apache Xerces jar to your application
- set the [net.sf.jasperreports.compiler.xml.parser.cache.schemas](https://jasperreports.sourceforge.net/config.reference.html#net.sf.jasperreports.compiler.xml.parser.cache.schemas) property to false

Also see https://github.com/TIBCOSoftware/jasperreports/issues/61 for a related discussion.
