### ISSUE TITLE
Band Expression Return Values no longer working with 7.0.0

### ISSUE THREAD

**Issue by kzander91** [TIBCOSoftware/jasperreports#445]
After migrating my reports to the new format as suggested in https://github.com/TIBCOSoftware/jasperreports/issues/442#issuecomment-2184710113, I noticed that the migration removed the `<returnValue/>` elments from my bands:
```xml
<band>
    <!-- ... -->
    <returnValue toVariable="bandTitle">
        <expression><![CDATA[$R{my.band.title}]]></expression>
    </returnValue>
</band>
```
With the new Jaspersoft Studio 7, I added the return value back in, but now I'm getting the following exception when loading the report file:
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `net.sf.jasperreports.engine.ExpressionReturnValue` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (ByteArrayInputStream); line: 236, column: 4] (through reference chain: net.sf.jasperreports.engine.design.JasperDesign["detail"]->net.sf.jasperreports.engine.design.JRDesignSection["band"]->java.util.ArrayList[0]->net.sf.jasperreports.engine.design.JRDesignBand["returnValue"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1887)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:414)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1375)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:274)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:361)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:246)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:30)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserialize(WrapperHandlingDeserializer.java:122)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:361)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:246)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:30)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:273)
	at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserialize(WrapperHandlingDeserializer.java:131)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserializeWith(SettableBeanProperty.java:579)
	at com.fasterxml.jackson.databind.deser.impl.MergingSettableBeanProperty.deserializeAndSet(MergingSettableBeanProperty.java:80)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserialize(WrapperHandlingDeserializer.java:122)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:104)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4905)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3885)
	at net.sf.jasperreports.jackson.util.JacksonUtil.loadXml(JacksonUtil.java:305)
```

Here's the setter, it accepts a list of `ExpressionReturnValue`:
https://github.com/TIBCOSoftware/jasperreports/blob/b478feaa9aab4375eba71de77b4ca138ad2f62aa/core/src/main/java/net/sf/jasperreports/engine/design/JRDesignBand.java#L161-L171
But there's no Jackson annotations on that interface, resulting in the above exception as Jackson doesn't know how to instantiate it:
https://github.com/TIBCOSoftware/jasperreports/blob/b478feaa9aab4375eba71de77b4ca138ad2f62aa/core/src/main/java/net/sf/jasperreports/engine/ExpressionReturnValue.java#L27-L40

---

Here's a minimal example that reproduces this:
```xml
<jasperReport name="test_report" language="java" uuid="c7a7c0dc-301a-4f63-9530-46741f65b19e">
    <variable name="bandTitle" class="java.lang.String"/>
    <pageHeader>
        <printWhenExpression><![CDATA[$V{bandTitle} != null]]></printWhenExpression>
        <element kind="textField" uuid="573defd2-0d05-4df7-b6b8-64d54ccf0d74">
            <expression><![CDATA[$V{bandTitle}]]></expression>
        </element>
    </pageHeader>
    <detail>
        <band>
            <returnValue toVariable="bandTitle">
                <expression><![CDATA["hello world"]]></expression>
            </returnValue>
        </band>
    </detail>
</jasperReport>
```

**Comment by teodord** [comment]
Thanks for letting us know. A fix has been committed and a new master SNAPSHOT has been published here:
https://jaspersoft.jfrog.io/ui/native/jr-ce-snapshots/net/sf/jasperreports/jasperreports/master-SNAPSHOT/
The fix will eventually reach Jaspersoft Studio too, but with a subsequent release and not immediately.

Thank you,
Teodor

**Comment by lucagaetani** [comment]
Hello, i've got the same problem, and using the last snapshot as compiler settings in Jaspersoft Studio doesn't work and it gives me the same error.

Thanks in advance for any answer
