### ISSUE TITLE
Version 7.0.0 Samples for updating/compiling reports "antupdate"

### ISSUE THREAD

**Issue by C4J** [TIBCOSoftware/jasperreports#450]
Now I'm maybe misinterpreting the process. It was my impression that I could bulk update my "pre version 7." reports via the command line. However when I copy one of my unaltered reports into the sample folder and run "ant test" I get an error like this one.
````
  [mkdir] Created dir: /Users/dave/Downloads/jasperreports-7.0.0/demo/samples/antupdate/build/reports
      [jru] Updating 4 report design files.
      [jru] File : /Users/dave/Downloads/jasperreports-7.0.0/demo/samples/antupdate/reports/com/bar/BarReport.jrxml ... OK.
      [jru] File : /Users/dave/Downloads/jasperreports-7.0.0/demo/samples/antupdate/reports/com/bar/audit_permissions.jrxml ... FAILED.
      [jru] Error updating report design : /Users/dave/Downloads/jasperreports-7.0.0/demo/samples/antupdate/reports/com/bar/audit_permissions.jrxml
      [jru] net.sf.jasperreports.engine.JRException: Unable to load report
      [jru] 	at net.sf.jasperreports.engine.xml.JRXmlLoader.loadXML(JRXmlLoader.java:172)
      [jru] 	at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:149)
      [jru] 	at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:120)
      [jru] 	at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:98)
      [jru] 	at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:89)
      [jru] 	at net.sf.jasperreports.ant.JRAntUpdateTask.update(JRAntUpdateTask.java:339)
      [jru] 	at net.sf.jasperreports.ant.JRAntUpdateTask.execute(JRAntUpdateTask.java:204)
      [jru] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
      [jru] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
      [jru] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      [jru] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
      [jru] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
      [jru] 	at org.apache.tools.ant.Task.perform(Task.java:350)
      [jru] 	at org.apache.tools.ant.Target.execute(Target.java:449)
      [jru] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
      [jru] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
      [jru] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
      [jru] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
      [jru] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
      [jru] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
      [jru] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
      [jru] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
      [jru] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      [jru] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
      [jru] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
      [jru] 	at org.apache.tools.ant.Task.perform(Task.java:350)
      [jru] 	at org.apache.tools.ant.Target.execute(Target.java:449)
      [jru] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
      [jru] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
      [jru] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
      [jru] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
      [jru] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
      [jru] 	at org.apache.tools.ant.Main.runBuild(Main.java:818)
      [jru] 	at org.apache.tools.ant.Main.startAnt(Main.java:223)
      [jru] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
      [jru] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
````

However if I load a report into JasperSoft Studio 7 it appears to be happy with it and will let me compile. 

Only if I save the report manually within JS and then use the antupdate script on the newly saved report does it appear to run.

I can supply a report sample if that helps.

Dave

**Comment by dadza** [comment]
Do you have a jasperreports-barcode4j jar on your project's classpath?

**Comment by C4J** [comment]
I am using the unmodified build.xml from your antupdate example. I just copied my reports into the same folder as the demo reports.

**Comment by C4J** [comment]
I've added some jars to the build.xml class path and now all my reports compile.

Thanks for the tip

Dave
