### ISSUE TITLE
 Issue with loading .jasper files in JasperReports 7.0.0

### ISSUE THREAD

**Issue by pvncoder** [TIBCOSoftware/jasperreports#455]
I recently migrated my `Spring Boot` application from `JasperReports` version `6.21.3` to `7.0.0`. The following code snippet, responsible for loading my compiled `jasper file (.jasper)` and generating a `JasperPrint`, worked fine in the previous version but now throws an error in the new version:
```java
try (InputStream stream = getClass().getClassLoader().getResourceAsStream(jasperReportType.getPath())) {
    return JasperFillManager.fillReport(stream, parameters, connection);
}
```
In `JasperReports 7.0.0`, I am encountering the following error:
```java
net.sf.jasperreports.engine.JRRuntimeException: Unable to load template
    at net.sf.jasperreports.engine.xml.JRXmlTemplateLoader.loadTemplate(JRXmlTemplateLoader.java:225) ~[jasperreports-7.0.0.jar:7.0.0-b478feaa9aab4375eba71de77b4ca138ad2f62aa]
    at net.sf.jasperreports.engine.xml.JRXmlTemplateLoader.load(JRXmlTemplateLoader.java:257) ~[jasperreports-7.0.0.jar:7.0.0-b478feaa9aab4375eba71de77b4ca138ad2f62aa]
    at net.sf.jasperreports.engine.xml.JRXmlTemplateLoader.loadTemplate(JRXmlTemplateLoader.java:115) ~[jasperreports-7.0.0.jar:7.0.0-b478feaa9aab4375eba71de77b4ca138ad2f62aa]
    at net.sf.jasperreports.engine.fill.JRFillReportTemplate.loadTemplate(JRFillReportTemplate.java:125) ~[jasperreports-7.0.0.jar:7.0.0-b478feaa9aab4375eba71de77b4ca138ad2f62aa]
    at net.sf.jasperreports.engine.fill.JRFillReportTemplate.evaluate(JRFillReportTemplate.java:93) ~[jasperreports-7.0.0.jar:7.0.0-b478feaa9aab4375eba71de77b4ca138ad2f62aa]
    at net.sf.jasperreports.engine.fill.JRBaseFiller.collectTemplates(JRBaseFiller.java:793) ~[jasperreports-7.0.0.jar:7.0.0-b478feaa9aab4375eba71de77b4ca138ad2f62aa]
    at net.sf.jasperreports.engine.fill.JRBaseFiller.collectTemplateStyles(JRBaseFiller.java:819) ~[jasperreports-7.0.0.jar:7.0.0-b478feaa9aab4375eba71de77b4ca138ad2f62aa]
    at net.sf.jasperreports.engine.fill.JRBaseFiller.collectStyles(JRBaseFiller.java:764) ~[jasperreports-7.0.0.jar:7.0.0-b478feaa9aab4375eba71de77b4ca138ad2f62aa]
    at net.sf.jasperreports.engine.fill.JRBaseFiller.loadStyles(JRBaseFiller.java:711) ~[jasperreports-7.0.0.jar:7.0.0-b478feaa9aab4375eba71de77b4ca138ad2f62aa]
    at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:592) ~[jasperreports-7.0.0.jar:7.0.0-b478feaa9aab4375eba71de77b4ca138ad2f62aa]
    at net.sf.jasperreports.engine.fill.BaseReportFiller.fill(BaseReportFiller.java:416) ~[jasperreports-7.0.0.jar:7.0.0-b478feaa9aab4375eba71de77b4ca138ad2f62aa]
    at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:121) ~[jasperreports-7.0.0.jar:7.0.0-b478feaa9aab4375eba71de77b4ca138ad2f62aa]
    at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:104) ~[jasperreports-7.0.0.jar:7.0.0-b478feaa9aab4375eba71de77b4ca138ad2f62aa]
    at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:529) ~[jasperreports-7.0.0.jar:7.0.0-b478feaa9aab4375eba71de77b4ca138ad2f62aa]
    at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:490) ~[jasperreports-7.0.0.jar:7.0.0-b478feaa9aab4375eba71de77b4ca138ad2f62aa]
    at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:928) ~[jasperreports-7.0.0.jar:7.0.0-b478feaa9aab4375eba71de77b4ca138ad2f62aa]
    at br.com.sysagro.service.JasperServiceImpl.generateReport(JasperServiceImpl.java:53) ~[classes/:?]
```
It seems that `JasperReports 7.0.0` is unable to locate the `.jasper` file in the resources directory. This issue did not occur in version 
`6.21.3`. I have verified that the path to the `.jasper` file is correct and that the file exists in the resources directory. Here is a screenshot of the code causing the issue:
![image](https://github.com/TIBCOSoftware/jasperreports/assets/51999509/f787a46f-21f8-47b6-94b5-289bb44ae1ff)
Please let me know if you need any further information or if there are any potential workarounds.

**Comment by teodord** [comment]
The exception is not about report files, but rather about style template files (*.jrtx).
Please note that in version 7, both *.jrxml and *.jrtx files have changed their syntax and you need to use Jaspersoft Studio 7 to convert them to the new syntax. Compiled report files (*.jasper) need to be recompiled using version 7 of the library.

I hope this helps.
Teodor

**Comment by gbouget** [comment]
> It seems that JasperReports 7.0.0 is unable to locate the .jasper file in the resources directory. This issue did not occur in version

I agree with teodord : it's probably a parsing problem due to syntax incompatibility since v7. You can detect the problematic file by adding a breakpoint to JRXmlTemplateLoader.loadTemplate(), line 115 and reading the parameter named location.

**Comment by pvncoder** [comment]
Thank you guys. The issue was with my `.jrtx` file. I opened it in Jasper Studio 7.0, made a fake change, and saved it to get the new syntax. It worked perfectly.

**Comment by Jai1507** [comment]
Hello @ALL
if anyone can help on the issue 

I have upgrade java 17, Tomcat 10 and upgraded the Jasper report lib 6.5.0 to 7.0.2 but I am facing a issue to generate a report and a console error --net.sf.jasperreports.engine.JRException: Error loading object from file: D:\CayRis\iris\WebContent\Reports\User_1\rb_studies_by_all_status.jasper, 
I don't have a .jrxml file in my project as of now, so what can be an alternative option to solve this problem or how to create a .jasper reports which are compiled for Jasper report 7.0.2

Thank you

**Comment by teodord** [comment]
You can use Jaspersoft Studio 6+ to load *.jasper files and save them back to source *.jrxml format.

I hope this helps.
Teodor

**Comment by Jai1507** [comment]
I tried to use Jasper soft 7.0.2 version but failed to convert older .jasper file to .jrxml, is there nay other way to do this? 
I was thinking if this way work to convert the okder .jasper file to .jrxml fiel using jasper soft 6.6.0 or any older version which might work then that converted .jrxml file to .jasper using jasper soft 7.0.2 to get the new .jasper file

**Comment by teodord** [comment]
I did not say you should use Jaspersoft Studio 7.0.2. I said you should use Jaspersoft Studio 6+, which includes 6.6.0, which you referred to.
