### ISSUE TITLE
NullPointerException on calling processImageRetainShape

### ISSUE THREAD

**Issue by fabiofdsantos** [TIBCOSoftware/jasperreports#7]
Sometimes, i'm getting an exception on calling **processImageRetainShape** (class: JRPdfExporter.java):
```
java.lang.NullPointerException
 at java.awt.color.ICC_Profile.activateDeferredProfile(ICC_Profile.java:1086) ~[?:1.7.0_80]
 at java.awt.color.ICC_Profile$1.activate(ICC_Profile.java:742) ~[?:1.7.0_80]
 at sun.java2d.cmm.ProfileDeferralMgr.activateProfiles(ProfileDeferralMgr.java:95) ~[?:1.7.0_80]
 at java.awt.color.ICC_Profile.getInstance(ICC_Profile.java:775) ~[?:1.7.0_80]
 at com.lowagie.text.Jpeg.processParameters(Unknown Source) ~[redoute-vendororderlifecycle-batch-deliverynotecrt-96.0.jar:96.0.0]
 at com.lowagie.text.Jpeg.<init>(Unknown Source) ~[redoute-vendororderlifecycle-batch-deliverynotecrt-96.0.jar:96.0.0]
 at com.lowagie.text.Image.getInstance(Unknown Source) ~[redoute-vendororderlifecycle-batch-deliverynotecrt-96.0.jar:96.0.0]
 at net.sf.jasperreports.engine.export.JRPdfExporter$InternalImageProcessor.processImageRetainShape(JRPdfExporter.java:1742)
```

This is a known bug in Java since 1.6:
"Loading ICC color profiles from multiple threads sometimes triggers a null pointer exception inside the JRE's ICC_Profile class."
 
Source: https://bugs.openjdk.java.net/browse/JDK-8058973

**Comment by dadza** [comment]
What JasperReports version are you using?

**Comment by ffsantos92** [comment]
@dadza, v6.3.1

**Comment by dadza** [comment]
The original exception is wrapped in a JRException, its stack trace should be included with "Caused by" if you're printing the full stack trace of JRException.

Like this (I forced a NPE by changing the code):

```
Exception in thread "main" net.sf.jasperreports.engine.JRException: java.lang.NullPointerException
	at net.sf.jasperreports.engine.export.JRPdfExporter$InternalImageProcessor.processImageRetainShape(JRPdfExporter.java:1747)
	at net.sf.jasperreports.engine.export.JRPdfExporter$InternalImageProcessor.process(JRPdfExporter.java:1604)
...
Caused by: java.lang.NullPointerException
	at net.sf.jasperreports.engine.export.JRPdfExporter$InternalImageProcessor.processImageRetainShape(JRPdfExporter.java:1742)
	... 9 more
```

**Comment by ffsantos92** [comment]
You're right. We are not printing the full stack trace.

**Comment by ffsantos92** [comment]
@dadza, I've re-opened this issue because of a "bug".

Since jasperreports is using Lowagie (deprecated since 2012), a possible workaround is to call `Image.getInstance(renderer.getData(jasperReportsContext));` synchronized.

**Comment by storoe1992** [comment]
Hello Fabio, i´m getting the same error, and i don´t know how to  figure out this -> "call Image.getInstance(renderer.getData(jasperReportsContext)); synchronized". Could you help me please. I´m writing a multi-thread application and at this time a resolve it whit a syncronized method, but is not the idea because it´s like a bottleneck in a multi-thread application. Thanks in advantage

**Comment by fabiofdsantos** [comment]
@storoe1992, You can follow my workaround and you will probably not notice a considerable bottleneck. Check it with [inspectIT](https://github.com/inspectIT/inspectIT) (an APM tool). 

Basically jasperreports must uses an alternative to Lowagie or a recent version of iText but I think it's not possible due to licensing.

If you need more help regarding this subject, please ask here: https://community.jaspersoft.com/project/jasperreports-library/answers

**Comment by storoe1992** [comment]
Hi @fabiofdsantos , I figure out it, the problem  is with the JPEG image so I use PNG image instead of JPEG image and everythins works fine. Maybe works for you if you go the same way. I open a question in StackOverFlow and make a reference to you, them I answer myself. I hope help the StackOverFlow community whit it. Thanks for reply me.

**Comment by fabiofdsantos** [comment]
@storoe1992, Thanks for your feedback!

In fact, I haven't went further on this bug and I don't know if you need always to load standard profiles, even for images with embedded ICC color space profiles.

I think it's not related with the "image format" but "how it was saved" (e.g. in the sRGB profile without embed any profile into image).

PS: Currently, I'm not able to perform more tests since I no longer work on the same company (or project which uses jasperreports).
